### ISSUE TITLE
Reihenfolge der Suchen/Ersetzen-Elemente bearbeiten?

### ISSUE THREAD

**Issue by Xendiadyon** [oveleon/contao-glossary-bundle#26]
Danke für die tolle Erweiterung. Ich hätte eine Frage bzw. einen Verbesserungsvorschlag:

In meinem Glossar möchte ich einmal das Wort "Scrum" und einmal das Wort "Scrum Master" verschlagworten.
Da möchte ich natürlich, dass immer wenn die Wortkombination "Scrum Master" verwendet wird, auch das entsprechend verschlagwortet wird.

Beispiel:
_Im Scrum ``->Scrum`` Framework unterstützt der Scrum Master **``->Scrum Master``** das Team dabei, Scrum ``->Scrum`` effektiv anzuwenden und sich kontinuierlich zu verbessern._

Aktuell wird es aber so geparsed:
_Im Scrum ``->Scrum`` Framework unterstützt der Scrum **``->Scrum``** Master  das Team dabei, Scrum ``->Scrum`` effektiv anzuwenden und sich kontinuierlich zu verbessern._
  
  
  
Es wird also niemals "Scrum Master" verschlagwortet, weil "Scrum" immer ein Teil des Glossareintrags "Scrum Master" ist.

Ich hätte aktuell zwei Workarounds:
1. Ich verwende nicht "Scrum" als Glossareintrag, sondern "Scrum Framework". Denn "Scrum" kommt schon ECHT häufig in meinen Texten vor :)
2. Ich erzwinge die Verschlagwortung von "Scrum Master" und Verwendung eines Insert Tags: _... unterstützt der ``{{glossaryitem::2}}`` das Team dabei ..._

Ich fände das aber super, wenn man die Spezifität irgendwie automatisch _(sortiere die Regex (oder die Glossareinträge) nach Länge, finde erst die längsten, dann die kürzeren)_ oder manuell _(Glossareintrag Scrum Master soll bevorzugt gefunden & ersetzt werden)_ festlegen könnte.

**Comment by zoglo** [comment]
@Xendiadyon could you install the dev-develop branch and test the new changes?

Remember that this does not work for macos due to how regex lookbehinds are still not supported after 6 years.
Only full word conversions work on Apple devices so the results may differ.

More information on safari:
https://bugs.webkit.org/show_bug.cgi?id=174931

They did implement it into the technology preview but it's not out yet (features and bugfixes usually stay there for years : ) )

**Comment by zoglo** [comment]
Fixed with https://github.com/oveleon/contao-glossary-bundle/releases/tag/2.1.0
